### ISSUE TITLE
Хрупкий файл настроек

### ISSUE THREAD

**Issue by johnnyshut** [infina15/oproxy#3]
Сдвинул пару строк, стер системные комментарии, и обработчик перестал видеть правила

[ПроверкиПроксиСервера.zip](https://github.com/infina15/oproxy/files/13798949/default.zip)

Комментарии о том, что можно трогать в скрипте только определенные области прочел. Но было бы удобнее если бы этих ограничений не было

**Comment by infina15** [comment]
@johnnyshut а куда экспорт потерялся у функций?

**Comment by johnnyshut** [comment]
вот я приворукий. вообще не знаю, как умудрился стереть
